
openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
paths:
  /pets:
    get:
      summary: List all pets
      parameters:
        - name: type
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A list of pets.
        '400':
          description: Invalid type supplied.
        '401':
          description: Unauthorized.
